refarch-machinesets:
  cloudProvider: vSphere
  infrastructureId:
  vsphere:
    networkName: vdpg-192.168.100
    datacenter: dc01
    datastore: openshift
    cluster: cluster01
    server: vcsa67.rtp.raleigh.ibm.com
    infraNodes:
      zones: 1
      nodeCount: 3
      diskGiB: 120
      memoryMiB: 16384
      numCPUs: 4
      numCoresPerSocket: 1
    storageNodes:
      zones: 1
      nodeCount: 3
      diskGiB: 120
      memoryMiB: 65536
      numCPUs: 16
      numCoresPerSocket: 1
    cloudpakNodes:
      zones: 1
      nodeCount: 0
      diskGiB: 120
      memoryMiB: 32768
      numCPUs: 8
      numCoresPerSocket: 1

refarch-infraconfig:
  argo:
    namespace: argocd
    serviceAccount: argocd-server
  registry:
    storageClassName: ocs-storagecluster-cephfs
    replicas: 2
  ingress:
    replicas: 2

refarch-storageconfig:
  ocs:
    installOCS: true
    channel: stable-4.6
    sizeGiB: 512
    storageClass: thin
