apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: tools
spec:
  encryptedData:
    .dockerconfigjson: AgB+VOn+OM1tMGuj5/x6VZ2JacMI/pKHYIKmvGvc4N0XQEho+iwEawDFzGqE58z4RlYTegJs2F33n422ln0WL/lcZJrGuC2QWkzDIcdaS3qJDTf7y44awn1/NKWJISkvi67ltTu3WCSaq9PjekYNndfYPiyn/O/ckVOMxjtZb1pn9/3mA1Y8C/5Bp1n6IRZEdq/oPsF3teP2g1wRc0lY27KlFI9c57pnHR6LruuyyXPGvFJQHNRNNYftqyp+9zvHoreqCmwFKr4CSH9ipV7Np15K+D0NM6PwDnrTLqBZVl2SBN6PK6kdZdaizjjj5kZT1NZ+/oYxx8w1vGxowF+RMkynBFSN1Yqrz2jypWckuSnxQ9+m++dgtUruyN5dS2xJ5z4aoZONTRZuSme1qoJp8jT8hHQRcT+6Yh1UrxHzbj8pkwTvGGxhCvoX+3Bg5/6wffo4I/nZJlj//IG4OAwtQE5iEyUU5nj3yB613WLO765eJgL20vm7NN5TgOTQnETyF/YfWVSaaxWJrmHd1kSSqEOcyIsFJJcl402LXWe8rdHOFkeNwINORCt1XPEIw2R/9nfgMXXM3lT5q4j6NM3eFGBkWBeiO7z2IBF17/oFDwGX8miKkYOiRZva1g7yeY9ZPQioK3ODWI14ujopxim53wlY+yRgJvHwBuLq8Tq9ZpA0kiIMANLpgQW871mGBiHBscQ9tKWavmv2HXRV03BG2huBmbIHD2IQ382x/bgRE96rDFy+eKIaCk292frhPLq8tDQGFx66U5tvKMBZ4lb47EtzKmQxbKwCpQIU5wPWy1Oa4cLSXserBomyWY0F/QZl/Uwb8QthOMSynj5N6DBmNxoRggSWJg+uZmdS9fMkeUYXSStLnvEr8EWvl+2Bujq0gHQkzd215YFvF0HAZFjN9nXTECzh+YDYyQoQIUc0KZSiCVCVk/oMuCoFlw7LBJ8vbrFcrnZ/wdQuN6hSqQ0IhFGpY1thiswcwMsNp7FZIhi6BQCcmFN1pj2QT8wdSqFbmSIEdC5T2xAcHUHNPLvgFDsUDIrRX5SNVr/TT7pHBNFKSa3OKWDaxGVzLLJUOvUWMIddfEvC0/YhWRV9Fmpat4ds+Lt06Zh5g3qEaGL5cNiFRYMyM2ms8sx6kgKI2oFYF7oqFApWyQg9Qh1m7WLZkp8v2mKsYI88TYZv+8HsBQ4TMQFca24y++3nL4odDlbXHoJ8P6l782ZGOsUNt431PqP0s5+jOf+g8Mlb/4tmFLsIEYd4Y3yAbRXhuH0slfk8zE7Z44IOp1PNsuHpw8gU1ZHlMgrG8WDHsMRJDIzBProkAmS6zJAB4304dgjCdtslIbnf
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: tools
    type: kubernetes.io/dockerconfigjson

