apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: tools
spec:
  encryptedData:
    .dockerconfigjson: AgAfAEjSHPAQLElD2KMz/yOk0oe0jnwlwT7NLZ6C0yEHCFpimU7/XzhvYkynCE1RtbLOmfsHXfDEJqPx5vMoXpaKNStfmSQaa6luOGcAZagzBxETht08gr2UOtyS/Fz/PSAyA1rlT4wGc4A6wF/3LDrocP6pnazGs3jubpO2Bf2VVZa2Gdz5vzsYKzEPW/Y9uOGDGf2/lJ3a+495oBxYqX+ADlO6J6H7/X/ao091495OttASe4JJhaNlxZg0ouHsQ0XuwczgcMyPBH+hE6DtvYDlvjk0sDKTTBXlrReeN/su8xxphoLUhPS6CR3oh/iajR0fXH4nQIU3QTcrzRpgg6ruxWXnE8i9AuMEYXpeQKDI5n7bgty4fdwJRBqm3HXW/16iAHqD6fjTHhqRa7+dKSspxh5Ft4HOmEjuzSJ2GAhkcZSZVEEic6biJmD6uQQHs+4jgIEBnbzLK/K5rAnAGtWVXGUERHnGMbQ7oA9o2CysWevPyAgqoDkHcFPhv7iRAwJoBnA1BFS7hNNiLi0AXhjIGdicyx3dbSzdUiD+T8NqjJJ8dh++oF3GMQXDHuj/fLBz/ojvQtw0xCThlUytLgN6tdgwvM3ByeYlbF9Re0JepUDfQfE2PBENFGB68jQvQC7hxKDQKKQWojEVCWhTtKidA+eBCO2LkdBnXp3BhDE2rHZfJN7Q2LPZ3t6hUrdtzeGfbQY07sV+VoWuF9fiiU5FT28yLkHJdW7h/fgXUBHosZ9mLpuQ90Q5Cr3IoFFHtjr+wHxyQsGyzbN2SBssL7vaw3Xib4NJwkaByedmKggT/z5F0O/+XZriZVQSrDaWcO6HNdYpEXHkNK7/D3szXbH62zV1BwEzT8kTmgNuDXQjSuaNQ6CRSM2BQbcVslMWgK2sewreuVfL1HBIxt9YAEFsPreGf/dchc9qu75Rmv5+/aM4cHlegjoB+KvgJ4XLqA1AeuBxw+cJQTR+yG/6joI8Bqazbh8xaxcjuBF/eDHQtk/vg59pdIgHSMFqbMWX6RyAG0FO2XjrrC1B7iZ8tE2OO53B4CgO3ZnKtsbYsM6J+8yXX/8oPKsw4o4crhMzuVNLGpGWvJ1NiUME7UTHgShv8SP0kgF4cMxHkfwqu6mWHNo7i4RWf63PmgfVpbSRf/McRx8/h9nYnb8/LetY0MhHRajYMkxBNwb6hcq+eBoTFFTlk6dRo3SxkJX9WqRs6eMpJqRFpZQyd/EM0y3Z1FpDyHua/BadLPgSSAMBuSfLa6q5OK6FfiW/v81bFCfZTQJLEsmEfXpyOlAzIlB7CN4ruh49ozKGzMJEdy5ElsEiuQzbryAQEsBI4kSfNdQBpFG6EImc1iV95CQYsvWKhwYB82Dg
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: tools
    type: kubernetes.io/dockerconfigjson

