apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 3-infra/namespaces/istio-system
    repoURL: https://github.com/cloud-native-toolkit/multi-tenancy-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
