apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-dev
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 3-infra/namespaces/dev
    repoURL: https://github.com/csantanapr/multi-tenancy-gitops.git
    targetRevision: bringup
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
