apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-instance
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  labels:
    gitops.tier.group: cntk
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: instances/cert-manager
    repoURL: https://github.com/cloud-native-toolkit/multi-tenancy-gitops-services.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
