apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-platform-navigator-instance
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  labels:
    gitops.tier.group: ibm-cloudpak
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: services
  source:
    path: instances/ibm-platform-navigator
    repoURL: https://github.com/cloud-native-toolkit/multi-tenancy-gitops-services.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
