apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-cp4a
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    gitops.tier.layer: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: applications
  source:
    repoURL: "" # Populated by kustomize patches in 3-apps/kustomization.yaml
    targetRevision: "" # Populated by kustomize patches in 3-apps/kustomization.yaml
    path: cp4a/config/cloudpak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
