apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-pipelines-operator
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/active/operators/openshift-pipelines
    repoURL: https://github.com/cloud-native-toolkit/multi-tenancy-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
