apiVersion: v2
name: tekton-pipeline-scc
version: 0.1.0
appVersion: 1.16.0
description: Tekton pipeline service account configuration
dependencies:
  - name: service-account
    version: 0.5.0
    repository: https://cloud-native-toolkit.github.io/toolkit-charts/

