apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-storage-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 1-infra/namespaces/openshift-storage
    repoURL: https://github.com/poonamzham/multi-tenancy-gitops
    targetRevision: demo-mq-v2-poonamzham
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
