apiVersion: v1                    
kind: Namespace
metadata:
  name: argo-helm                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: argo
  namespace: argo-helm
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - argo
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: argo-helm
  namespace: argo-helm
spec:
  type: HelmRepo
  pathname: 'https://argoproj.github.io/argo-helm/'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: argo
  name: argo-subscription
  namespace: openshift-gitops
spec:
  channel: argo-helm/argo-helm
  name: argo-cd
  packageOverrides:
  - packageName: argo-cd
    packageAlias: argo-cd
    packageOverrides:
      - path: spec
        value:
          route:
            enabled: true
          openshift:
            enabled: true
  packageFilter:
    version: "3.1.1"
  placement:
    clusters:
    - name: cluster3 
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: argo
  name: argocdv2
  namespace: argo-helm
spec:
  clusterSelector:
    matchLabels:
      'argocd': 'argocd-v2'
status:
  properties:
    decisions:
      items:
      - properties:
          clusterNamespace: openshift-gitops