apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: mq-self-signed-ca-cert
spec:
  commonName: any.common.name
  isCA: true
  dnsNames:
    - *.<cluster-domain>
  secretName: mq-self-signed-ca-cert
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
