---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  labels:
    gitops.tier.layer: applications
spec:
  sourceRepos: []  # Populated by kustomize patches in 3-apps/kustomization.yaml
  destinations:
  - namespace: ci
    server: https://kubernetes.default.svc
  - namespace: dev
    server: https://kubernetes.default.svc
  - namespace: staging
    server: https://kubernetes.default.svc
  - namespace: prod
    server: https://kubernetes.default.svc
  - namespace: tools
    server: https://kubernetes.default.svc
  - namespace: ibm-common-services
    server: https://kubernetes.default.svc
  - namespace: cloudpak
    server: https://kubernetes.default.svc
  - namespace: openshift-gitops
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  # TODO: SCC needs to be moved to 1-infra, here for now pipeline sa for buildah
  - group: "security.openshift.io"
    kind: SecurityContextConstraints
  - group: "rbac.authorization.k8s.io"
    kind: ClusterRole
  - group: "rbac.authorization.k8s.io"
    kind: ClusterRoleBinding
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to my-project
    policies:
    - p, proj:my-project:read-only, applications, get, my-project/*, allow
    groups:
    - argocd-admins
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    gitops.tier.layer: gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: applications
  source: # repoURL  and targetRevision populated by kustomize patches in 3-apps/kustomization.yaml
    path: 0-bootstrap/others/apic-multi-cluster/template-gateway-analytics-cluster/3-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
