apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-cpd-scheduling-operator
  annotations:
    argocd.argoproj.io/sync-wave: "230"
  labels:
    gitops.tier.group: ibm-cloudpak
    gitops.tier.layer: services
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ibm-common-services
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: operators/ibm-cpd-scheduling-operator
    helm:
      values: |
        ibm-cpd-scheduling-operator:
          subscriptions:
            ibmcpdscheduling:
              name: ibm-cpd-scheduling-catalog-subscription
              subscription:
                channel: alpha
                installPlanApproval: Automatic
                name: ibm-cpd-scheduling-operator
                source: ibm-operator-catalog
                sourceNamespace: openshift-marketplace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
