apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-ace-operator
  annotations:
    argocd.argoproj.io/sync-wave: "230"
  labels:
    gitops.tier.group: ibm-cloudpak
    gitops.tier.layer: services
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: operators/ibm-ace-operator
    helm:
      values: |
        ibm-ace-operator:
          subscriptions:
            ibmace:
              name: ibm-ace
              subscription:
                channel: v4.2
                installPlanApproval: Automatic
                name: ibm-appconnect
                source: ibm-operator-catalog
                sourceNamespace: openshift-marketplace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
