apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "100"   
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 1-infra/namespaces/istio-system
    repoURL: https://github.com/Jibbscript/multi-tenancy-gitops.git
    targetRevision: demo-mq-v2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
