apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools
  annotations:
    argocd.argoproj.io/sync-wave: "100"   
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 1-infra/namespaces/tools
    repoURL: https://github.com/cloud-native-toolkit/multi-tenancy-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
