apiVersion: v2
name: ibm-cp4i-operators
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: ibm-cp4i-operators
    version: 0.2.1
    repository: https://cloud-native-toolkit.github.io/toolkit-charts/
