apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-mq-staging-instance
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/instances/namespace-staging/mq-infra
    repoURL: https://github.com/poonamzham/multi-tenancy-gitops
    targetRevision: demo-mq-v2-poonamzham
    helm:
      valueFiles:
      - values.yaml
  syncPolicy: {}
