apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh-instance
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  labels:
    gitops.tier.group: cntk
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/instances/service-mesh
    repoURL: https://github.com/Jibbscript/multi-tenancy-gitops.git
    targetRevision: demo-mq-v2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
