apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-mq-prod-instance
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/instances/namespace-prod/mq-infra
    repoURL: https://github.com/Jibbscript/multi-tenancy-gitops.git
    targetRevision: demo-mq-v2
    helm:
      valueFiles:
      - values.yaml
  syncPolicy: {}
