apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh-instance
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/active/instances/service-mesh
    repoURL: https://github.com/cloud-native-toolkit/multi-tenancy-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
