apiVersion: v2
name: instana-agent
version: 0.1.0
appVersion: 1.16.0
description: Instana Agent
dependencies:
  - name: service-account
    version: 0.5.0
    repository: https://cloud-native-toolkit.github.io/toolkit-charts/
  - name: instana-agent
    version: 1.2.14
    repository: https://agents.instana.io/helm
