apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  labels:
    gitops.tier.group: cntk
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: 2-services/operators/jaeger
    repoURL: https://github.com/poonamzham/multi-tenancy-gitops
    targetRevision: demo-mq-v2-poonamzham
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
