apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/operators/sealed-secrets
    repoURL: https://github.com/<github-org>/multi-tenancy-gitops.git
    targetRevision: <github-branch>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
