apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  labels:
    gitops.tier.group: cntk
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/operators/sealed-secrets
    repoURL: https://github.com/cloud-native-toolkit/multi-tenancy-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
