apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgB/JPkRDhaxullVsUNmA+EyPTHzHOz5JqJgTIuSxkgjFsk6ojAkOF0ZjAPKbAAQe/dmFH83TdoNDVUClovZAMMmOFpflc//7ErFLo+iLI0z11zRuMA7TJQAQve+AyzkrcZxJAsiaGZ7Et+/ykWwyK5Dhz6vtS7c4KSMuz720PcAjs8FSDQs0aex3+Pti8pb2egCsCXY2EtglL0COHpFb3t1a591RzUmHCTCa52lRsb82w2AK7cc+DDRQ3Fers5uvIw6/n2cbPceAgP9wotoNcLUY2LQql4Y4K90qpdy3BYiUUESxnLbYFo7jJOT4bqK3VWkbx6PM8NqfM+fklhRp71R87opG2M99zRSmC0X7L+od+f9hGkfvgO5eUq8VGtfE006yubkNJH91nam/SHltGs+WOF927ksRw96gWD/EHCrU8qlz62RYZA0V+2ZnwnLOAWgEMmO8rpYaIKbnWMbBtcW5rSbqPupoDD7rzVzN1LvghVwHWMQkL274grW5aoGmElfhgCSwRqRJDK+GrmvWw8FRiu3I1d5g6QXMcp7ocyWqL67xa2xve8DYhNd7EPOrUb+5nTIfHpvEczoXTwrTWm8S/3h/i+2OH5qRs/IuKWdq4IfklOlkUEykVgNkJ7JyswiLGBjoMua5Ww3ToHO58AfrIVIPx6SCUd93+geSiMYsrXhmaa1IrWcYz0gpCbpwxq/lM+DAbyxyFrL7e8HfeCXaQhce5hjZP6krT3425R9v/Ftmrtwl8lxgi9XeMggh6DwzsOg1ewSFZkh3xzB5I/VqFZ2ntFZZfYm0F0h6hOaDZDGu5Y7dGRlOGDOeP5nljsKOv3haiA/VWRsm9bFfmSV2/agPZMrAc3wwRCw0OGxbOqY/e2vXi12HVJjFHGRwRCyMhKVeZ29N+a8aOW8n2rrcTLqZojLJUa53DFJeU3KWQ==
    IBM_ENTITLED_REGISTRY_USER: AgBkzEiZs6VTmr+ISWoa1/3ZYYi54jSdeng4T8eI4ni8neW4I7pgmqnOSGft3v0A0ParT3rlOM3WQzEcFO+5x7aVaW8ICzWlR3nTkAqBhsVmkavEEZxKBVfH3TTOwOnNTMXejYSX0V2ee577yp5e2UVnXEc0LcgfoXRaIhqQT8hykiqddC8UW8O9wniHnc+aVwCzWMajVfsl3xQUz6wjROfPxkNzC3iVYDCHruUBm+b2+lhLGFnpp2QsHe/iuvPXHMC0n7KDzC27HdaOdI378eyo89Sxwp0rpgsncvQCLLWstUW8B6gDHmLmhX7NP+U739tfVipvPgmh6H8cL7ZG5dtvKy9MtJ9SKeyLJFp3/9K3w8IMuMTnxabQbxMSKFsD3ucH9+DLn7g1iDp+XGb1aek/ktQDv3D1b4fNz7xExfq8fJyLu4gBMnEJ8RfC03IHBTRmlzW9+OeesWBtztbK794pg+fj0UiTH2KnT7EItVUp68Nief4wxXFJ6DgO29g3xKx2xuAnYMzMH5Ef1X9L9hUcVCwu6BvDEee8R3EN0JMrh3UECyxOtnlOtlxPzmKI2C8RBORH4xA25UK8cartXgNAGh9zZgk8YDpqRRz+eSEG2rnX8Ru8GD4+ZTD1dYvWpB9xCPNazdtcFT7pnWNE/P/70TYIVnrB6NWtDQztwtRnd0V+GkGJH2kG/+CRqBZR8OKPEA==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci
    type: Opaque

