apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-self-signed-ca-cert
  labels:
    gitops.tier.group: cntk
spec:
  commonName: any.common.name
  isCA: true
  dnsNames:
    - >- 
      *.<cluster-domain>
  secretName: mq-self-signed-ca-cert
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
