apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mq-quarkus-app-staging
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: 3-apps/instances/namespace-staging/mq-quarkus-app
    repoURL: https://github.com/Jibbscript/multi-tenancy-gitops.git
    targetRevision: demo-mq-v2
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
