apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infraconfig
  annotations:
    argocd.argoproj.io/sync-wave: "102"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: infraconfig
    repoURL: github.com/cloud-native-toolkit/multi-tenancy-gitops-infra.git
    targetRevision: master
    helm:
      values: |
        refarch-infraconfig:
          cloudProvider:
            name: "aws" # set to aws or vsphere,
            managed: "false" # set to true for ARO or ROSA
          argo:
            namespace: openshift-gitops
            serviceAccount: argocd-cluster-argocd-application-controller
          registry:
            storageClassName: ocs-storagecluster-cephfs
            replicas: 2
          ingress:
            replicas: 2
          image-registry-hook-job:
            name: infraconfig-postsync
            namespace: tools
            hook:
              enabled: true
              hooktype: infraconfig-postsync
            hookdeletepolicy:
              enabled: true
              hookdeletepolicytype: HookSucceeded
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
