apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: integration-navigator
spec:
  license:
    accept: true
    license: L-RJON-BZFQU2
  mqDashboard: true
  version: 2021.2.1
  storage:
    class: ibmc-file-gold-gid
  replicas: 2
