apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-instana-agent
  labels:
    gitops.tier.layer: infra
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: instana-agent
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: namespaces/instana-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
