apiVersion: v1
data:
  branch: demo-mq-v2-poonamzham
  host: github.com
  org: poonamzham
  owner: poonamzham
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops
  url: https://github.com/poonamzham/multi-tenancy-gitops.git
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
  namespace: ci
