apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory
spec:
  destination:
    namespace: tools
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: 2-services/operators/artifactory
    repoURL: https://github.com/hollisc/multi-tenancy-gitops.git
    targetRevision: demo-cntk
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
