apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasks
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: services
  source:
    path: tasks
    repoURL: https://github.com/IBM/ibm-garage-tekton-tasks.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
