apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: services
  source:
    path: ibm/us-east/toronto1/ocp-clusters/pre-prod-1/2-services/operators/sealed-secrets
    repoURL: https://github.com/<github-org>/multi-tenancy-gitops.git
    targetRevision: demo-mq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
