apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-mq-server-cert
spec:
  dnsNames:
    - *.mq-kam-gitops-2-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-south.containers.appdomain.cloud
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-mq-cluster-issuer
  secretName: mq-server-cert
  subject:
    organizations:
    - ibm
